name: Release
on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  precompile_nifs:
    strategy:
      fail-fast: false
      matrix:
        nif: ["2.17", "2.16", "2.15"]
        job:
          - { target: aarch64-apple-darwin, os: macos-latest }
          - {
              target: aarch64-unknown-linux-gnu,
              os: ubuntu-22.04,
              use-cross: true,
            }
          - { target: x86_64-apple-darwin, os: macos-15-intel }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-22.04 }
    runs-on: ${{ matrix.job.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}
      - name: Extract version
        run: echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> $GITHUB_ENV
      - id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: pikchr_nif
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          project-dir: "native/pikchr_nif"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

  publish_release:
    needs: precompile_nifs
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with: { path: artifacts }
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.tar.gz
